FROM python:3.7.3-stretch

# Set the working directory to /app
WORKDIR /app/server

# Copy the current directory contents into the container at /app
COPY . /app/server

# Install any needed packages specified in requirements.txt
RUN pip install mysql-connector-python mysql2pgsql 
RUN pip install sqlalchemy
RUN pip install flask flask_sqlalchemy

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Command to run the application
CMD ["python", "app.py"]