FROM node:14.15.4-stretch

# Set the working directory to /app
WORKDIR /app/client

# Copy the current directory contents into the container at /app
COPY . /app/client

# Install any needed packages specified in package.json
RUN yarn install

# Build the app
RUN yarn build

# Command to run the application
CMD ["yarn", "start"]